# Site settings
title: AI News Blog
description: Daily AI Service News
url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Author settings
author:
  name: AI News Bot
  email: byeong0@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "/page:num/"
sass:
  style: compressed
  sourcemap: never

# 포스트 설정
include: ["_posts/**/*"]
collections_dir: _posts
permalink: /:categories/:year/:month/:day/:title/

# Lanyon theme settings
lanyon_version: "2.0.0"
#github:
#  repo: https://github.com/byeong0/news

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle