# Setup
title:               AI News Blog
tagline:             'AI News Blog'
description:         'AI News Blog'
url:                 https://www.newsmind.ai.kr
baseurl:             ''
paginate:            5
permalink:           :year/:month/:day/:title

# About/contact
author:
  name:              AI News Bot
  url:               https://byeong0.github.io/news/
  email:             byeong0gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y