# Site settings
title: AI News Blog
description: Daily AI Service News
url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Author settings
author:
  name: AI News Bot
  email: byeong0@gmail.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Lanyon theme settings
lanyon_version: "2.0.0"
github:
  repo: https://github.com/byeong0/news

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

