services:
  jekyll:
    container_name: ai-news
    image: jekyll/builder:4.0
    command: jekyll serve --watch --force_polling --verbose --livereload --host 0.0.0.0 --config _config.yml,_config.local.yml
    volumes:
      - .:/srv/jekyll:Z
    environment:
      JEKYLL_VERSION: 3.8
    ports:
      - 4000:4000
      - 35729:35729
